### ISSUE TITLE
can't make any app upgrade after removing fallback app

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/fallback_ynh#30]
Hello @maniackcrudelis o/

i just create a topic in the forum, i can't upgrade any app after removing fallback from the (master) server, 
https://forum.yunohost.org/t/cant-upgrade-apps-anymore/19728

your help should be helpfull, 
i think fallback isn't appropriate anymore with the "new" ynh version, something is wrong (but i don't find what/where/howto fix)

thx for your help ;)

i duplicate it here:

### My YunoHost server

**Hardware:** VPS bought online (proxmox + vm ynh_server)
**YunoHost version:** 
```
root@krashboyz:~# yunohost -v
yunohost: 
  repo: stable
  version: 4.3.6.3
yunohost-admin: 
  repo: testing
  version: 4.3.4.1
moulinette: 
  repo: stable
  version: 4.3.3.1
ssowat: 
  repo: stable
  version: 4.3.3.1
```
**I have access to my server :** 
Through SSH : YES
Through the webadmin : YES 

**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : 
**If yes, please explain:**
added the fallback app, then removed it few days after; i tried to reinstall fallback after the bug incomming, but it doesn't fix it.  (it is not really a tweak :/ )

### Description of my issue

i can't upgrade my apps anymore via cli and webadmin.
|command|result|error log|
|-|-|-|
|`yunohost tools update` |->  works fine :white_check_mark: |
|`yunohost tools upgrade system` |-> works fine :white_check_mark:
|`yunohost tools upgrade apps` |-> is broken :x: |-> error log: https://paste.yunohost.org/raw/oterigavul |
|`yunohost app upgrade wikijs` or any other installed app |-> is broken :x: | -> error log: https://paste.yunohost.org/raw/ujecuwobuv |

i searched a bit everywhere, tried to force to upgrade moulinette without any better result, 
i'm a bit locked and need your kindless help.

i don't see what i could done wrong, 
my server is old old old, perhaps some old stuff somewhere ?

tell me if you need any more details.

thx for your help (i understand french and english)

isAAAc
